### ISSUE TITLE
[JST-25] Add tests for alter table statements

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/js-tableland#486]
When the alter table syntax is supported by the protocol we should add tests to the SDK that ensure creating, inserting, altering, and inserting to the new table works as expected.

<sub>From [SyncLinear.com](https://synclinear.com) | [JST-25](https://linear.app/tableland/issue/JST-25/add-tests-for-alter-table-statements)</sub>

**Comment by brunocalza** [comment]
@joewagner I'd like to try working on this one. What's the usual flow so that I can test a version of `go-sqlparser` in `js-tableland` ? I've created a PR in the `wasm-sqlparser` [https://github.com/tablelandnetwork/wasm-sqlparser/pull/198](https://github.com/tablelandnetwork/wasm-sqlparser/pull/198) 

a side comment

when i run `npm test` in `wasm-sqlparser` i'm getting 

```
Warning: Cannot find any files matching pattern "test/*.test.ts"

Error: Cannot find module '/Users/brunocalza/projects/js-tableland/wasm-sqlparser/test/setup.ts' imported from /Users/brunocalza/projects/js-tableland/wasm-sqlparser/node_modules/mocha/lib/nodejs/esm-utils.js
    at finalizeResolution (/Users/brunocalza/projects/js-tableland/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:352:11)
    at moduleResolve (/Users/brunocalza/projects/js-tableland/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:801:10)
    at Object.defaultResolve (/Users/brunocalza/projects/js-tableland/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
    at /Users/brunocalza/projects/js-tableland/node_modules/ts-node/src/esm.ts:218:35
    at entrypointFallback (/Users/brunocalza/projects/js-tableland/node_modules/ts-node/src/esm.ts:168:34)
    at /Users/brunocalza/projects/js-tableland/node_modules/ts-node/src/esm.ts:217:14
    at addShortCircuitFlag (/Users/brunocalza/projects/js-tableland/node_modules/ts-node/src/esm.ts:409:21)
    at resolve (/Users/brunocalza/projects/js-tableland/node_modules/ts-node/src/esm.ts:197:12)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1098:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:438:21)
    at importModuleDynamically (node:vm:389:46)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at Object.exports.doImport (/Users/brunocalza/projects/js-tableland/wasm-sqlparser/node_modules/mocha/lib/nodejs/esm-utils.js:35:34)
    at formattedImport (/Users/brunocalza/projects/js-tableland/wasm-sqlparser/node_modules/mocha/lib/nodejs/esm-utils.js:9:28)
    at Object.exports.requireOrImport (/Users/brunocalza/projects/js-tableland/wasm-sqlparser/node_modules/mocha/lib/nodejs/esm-utils.js:42:34)
    at Object.exports.loadFilesAsync (/Users/brunocalza/projects/js-tableland/wasm-sqlparser/node_modules/mocha/lib/nodejs/esm-utils.js:100:34)
    at Mocha.loadFilesAsync (/Users/brunocalza/projects/js-tableland/wasm-sqlparser/node_modules/mocha/lib/mocha.js:447:19)
    at singleRun (/Users/brunocalza/projects/js-tableland/wasm-sqlparser/node_modules/mocha/lib/cli/run-helpers.js:125:15)
    at exports.runMocha (/Users/brunocalza/projects/js-tableland/wasm-sqlparser/node_modules/mocha/lib/cli/run-helpers.js:190:10)
    at Object.exports.handler (/Users/brunocalza/projects/js-tableland/wasm-sqlparser/node_modules/mocha/lib/cli/run.js:370:11)
    at /Users/brunocalza/projects/js-tableland/wasm-sqlparser/node_modules/yargs/build/index.cjs:443:71
```

**Comment by joewagner** [comment]
@brunocalza As you know, there's quite a few moving parts, but in general the steps to setup testing of specific branches will be:
- clone all the repos in the same directory
- checkout the branches you want to be using in each of the repos
- run the install and build steps for each repo that you are going to be using a custom build for.  Note: for our npm based packages, if you run into trouble try deleting the `/node_modules` directory then doing the install and build steps.  e.g. run `rm -rf node_modules && npm install && npm run build`
- Next I would use `npm link` to connect each of the npm packages.  The `npm link` command is know for being easy to use incorrectly, and you can potentially use `npx` as an alternative.  I am most familiar with `npm`, so I'll explain the steps to use it, but if you want to know more details here is an article explaining some of the trickiness. https://hirok.io/posts/avoid-npm-link.  
  - To do the linking: 
  - go into each repo that you want to use, and run `npm link`.  note: you have to do this after running `npm install`, because you can potentially undo linking if run install after linking.
  - inside of the local-tableland repo you'll want to run `npm link ../js-tableland ../js-validator`
  - inside of the js-tableland repo you'll want to run `npm link ../wasm-sqlparser`
- at this point you are setup to test the sqlparser and js sdk interactions, but keep in mind you'll also need to build link the Validator if you want to be running a specific commit of that repo.

**Comment by brunocalza** [comment]
circling back to this @joewagner i've managed the other day to get those tests running locally, but for some reason I am not able to do that anymore, would mind taking a look? [https://github.com/tablelandnetwork/js-tableland/pull/500](https://github.com/tablelandnetwork/js-tableland/pull/500)

all other repos have respective branches, except for `go-sqlparser`where the change is already in main

another question: what's the workflow for updating js-tableland since it depends on wasm-parser and js-validator for tests? gotta first wait for the release?

**Comment by joewagner** [comment]
> circling back to this @joewagner i've managed the other day to get those tests running locally, but for some reason I am not able to do that anymore, would mind taking a look? #500
Yep! I can definitely take a look

> another question: what's the workflow for updating js-tableland since it depends on wasm-parser and js-validator for tests? gotta first wait for the release?
You can build and link everything locally, but it is a lot less complicated if you wait for the release
